### ISSUE TITLE
Feature Request: Ability to block or mute an account on foreign instance

### ISSUE THREAD

**Issue by tinglycraniumplacidly** [Lartsch/FediAct#12]
And I guess whatever else is normally available and makes sense to implement, via the 3 dot dropdown menu.

❤️

**Comment by Lartsch** [comment]
Aye, working on an update to support the following actions from toots or profile pages:
- Mute, Unmute
- Block, Unblock
- Domain block, Domain Unblock
- Bookmark (for v3 only, which has no bookmark icon in the action bar)

**Comment by Lartsch** [comment]
This is now added in 0.9.8, but only for v4 instances (which I hope is sufficient, as I do not want to inject 3-dot button for v3 instances)

**Comment by tinglycraniumplacidly** [comment]
sick! can't wait to try. much appreciated!
