### ISSUE TITLE
Feature request: per-container home instance setting for better multi-account support

### ISSUE THREAD

**Issue by confluence** [Lartsch/FediAct#13]
I manage two separate Mastodon accounts: my main personal account, and an institutional account on a different instance which mostly posts, but occasionally needs to follow someone, boost something, etc..

I know that FediAct has a setting which prevents it from running on other instances if I am logged in there, and that solves a lot of problems. However, there are still two possible failure modes:

1. I want to follow an account on the second instance from my home instance account. I have navigated to the profile page on the second instance, where I am logged in, so FediAct is not running, so all my actions are executed on the second instance instead.
2. I want to follow an account outside the second instance from the second account. I have navigated to the profile page outside the second instance, so FediAct *is* running, so all my actions are executed on my home instance instead.

Currently I have solved this problem by logging into the second account only in a private window, and by disabling FediAct in private windows, but this is a bit clumsy.  It looks like Firefox's container tabs are designed to solve exactly this kind of problem, but FediAct's home instance setting appears to be global. It would be useful if it could be configured per container. Is this possible? I don't know if the container that a tab is running in is exposed in the API.

(Ironically, I think this would all be working smoothly if both my accounts were on the same instance -- each container would have separate cookies and be logged into a different account, but the instance setting wouldn't need to change.)

**Comment by Lartsch** [comment]
Hi, good suggestion. I will look into this, but I will priorize some other todos first (stability, bug fixes, smaller feature requests).

Thanks!

**Comment by Lartsch** [comment]
I'll close this in favor of #18 which also aims at better multi-account support.
