### ISSUE TITLE
Feature Request: Inject a #home link on non-home server sidebars

### ISSUE THREAD

**Issue by Bastlynn** [Lartsch/FediAct#15]
So we can easily navigate back to base? Or a top bar in general to make that navigation back easy?

**Comment by Lartsch** [comment]
Hi, good suggestion. Will add it for v4 instances, but now for v3.

**Comment by Bastlynn** [comment]
Yay! Thank you! <3

**Comment by Lartsch** [comment]
Added with commit https://github.com/Lartsch/FediAct/commit/3ae11ff11dcc46711d31431c09c450065ffd8585, included in the next update
