### ISSUE TITLE
Not working on wandering.shop

### ISSUE THREAD

**Issue by confluence** [Lartsch/FediAct#19]
I'm not sure how the add-on recognises that a page is a Mastodon instance, but I have noticed that it doesn't work on `wandering.shop` (a small instance where I follow a bunch of people).

**Comment by Lartsch** [comment]
Works fine here... Not sure what's the issue

**Comment by confluence** [comment]
Update: It started working after I reloaded the profile page! Initially I opened it together with several other tabs, which may have affected the speed with which the page loaded. Maybe it's some weird race condition? It seems odd that it would affect this specific instance (perhaps it's tied to the performance of the server?).
