### ISSUE TITLE
Using page-action instead to show FediAct is running / fix box blocking buttons

### ISSUE THREAD

**Issue by Freeplayg** [Lartsch/FediAct#20]
I personally think it could be a more elegant way of showing that FediAct is running, and possibly prevent the blocking of content in the future (when other platforms are supported)

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Page_actions

**Comment by Lartsch** [comment]
Hi, I'll look into it. If I remove the box, the toggle for #18 needs to go into the popup as well, not sure yet.

**Comment by Lartsch** [comment]
Okay, just noticed this:
![Screenshot_20221220-084005_Kiwi Browser](https://user-images.githubusercontent.com/2946228/208610487-02305e3a-fbf0-444b-b452-25218dabf994.jpg)

The box blocks two buttons, so it really must go.

**Comment by Lartsch** [comment]
I am not sure how page actions would work out for mobile browsers. As far as I know, they are displayed in the URL bar.

**Comment by Freeplayg** [comment]
I'm actually not sure about mobile either... But I wonder if the toggle/account switching could actually go into the page-action button as well (and the regular extension popup could let you add multiple servers like in the filtered servers list)

**Comment by Freeplayg** [comment]
*I think* according to MDN's table they work on Firefox for Android & Safari iOS, but I'm honestly a little bit confused by it https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/pageAction#browser_compatibility

**Comment by Lartsch** [comment]
I'll close this as I prefer to use the injected extension icon in the bottom right, which no longer blocks toot buttons in some cases. It's just easier to implement and easier for cross-browser.
