### ISSUE TITLE
Adding a copy link button to the More menu

### ISSUE THREAD

**Issue by Freeplayg** [Lartsch/FediAct#26]
Would be useful if you wanted to share the post or paste into your home server manually 

![image](https://user-images.githubusercontent.com/40742947/208747064-0ec99698-8c61-41c3-9812-0bfa292acbbe.png)

**Comment by Lartsch** [comment]
Yep, good suggestion. Thx

**Comment by Lartsch** [comment]
Added in https://github.com/Lartsch/FediAct/commit/d99d7bf48cc01678561e8fa544285a789d73ef5f, included in next update
