### ISSUE TITLE
UI is tiny in Firefox for Android

### ISSUE THREAD

**Issue by Freeplayg** [Lartsch/FediAct#27]
This is something I didn't realize when making the new UI and that I don't really know how to fix...
![Screenshot_20221220-155252](https://user-images.githubusercontent.com/40742947/208764812-8a49fb3b-c2f5-422e-9447-641a91611904.jpg)

**Comment by Freeplayg** [comment]
Oh wait, the `<meta name="viewport" content="width=device-width, initial-scale=1.0">` line in the HTML head isn't there anymore @Lartsch

**Comment by Lartsch** [comment]
Ah my bad! I'll re-add it. Not sure if that'll do the trick but good chance.

**Comment by Freeplayg** [comment]
Btw, that line you removed in the recent commit was for Firefox

![image](https://user-images.githubusercontent.com/40742947/208778445-f5cccbdf-4e36-45e6-9ee7-037af65e2618.png)

**Comment by Freeplayg** [comment]
This commit I mean https://github.com/Lartsch/FediAct/commit/8f2450f79b2c8f440ff5ba4fd2052341e36ea311

**Comment by Lartsch** [comment]
Oh, what does it do? Never seen that, thought it was some kind of leftover from testing. I'll readd it

**Comment by Freeplayg** [comment]
I forget where the MDN page for it was but it basically sort of makes the extension look more like the native UI the browser has

**Comment by Freeplayg** [comment]
(for example in the image I sent above, with it removed it doesn't use the browser's font)

**Comment by Lartsch** [comment]
Fixed in 0.9.8.4
