### ISSUE TITLE
API call can trigger unwanted behaviour on non-Mastodon sites

### ISSUE THREAD

**Issue by plttn** [Lartsch/FediAct#29]
Hey there! I've been running into this, and wasn't sure what caused it until just now, but with FediAct installed and enabled, anytime I browse to https://macrumors.com, I end up with an HTTP basic auth prompt appearing. This happens on both Firefox and Chrome. Interestingly enough, I don't see any requests in the extension network log that would be triggering this.

**Comment by Lartsch** [comment]
Hi there!

Just gave it a look. Seems like the API call that FediAct needs to make to determine if the site is a Mastodon instance triggers this.

macrumors.com possibly triggers the basic auth for all URLs starting with /api/...

I'll think about how to prevent this, thanks for the heads up

**Comment by Lartsch** [comment]
The only way I can think of to fix this is to drop the API call to /api/v1/instance and determine if it's a Mastodon site by checking for DOM elements.

**Comment by Lartsch** [comment]
Fixed in 0.9.8.4
