### ISSUE TITLE
Feature Request: Respect block/muted users/instances

### ISSUE THREAD

**Issue by tinglycraniumplacidly** [Lartsch/FediAct#3]
Hi, I absolutely love this extension!!!

I just upgraded today and was noticing the automatic faving/boosting (of posts I'd already fav'd boosted) as I was scrolling, which is so sick btw. And I thought, if this can be done, maybe this extension could also not load posts from people I've muted/blocked.

That would literally complete every issue I've had with browsing other instances. I'm not sure if it's outside the scope of what you'd envisioned for this extension, but it doesn't seem technically too dissimilar?

Thanks again!

**Comment by Lartsch** [comment]
Hi,
thanks for the feedback and your suggestion.

It's definitely possible (like, grabbing your muted/blocked users every 30 minutes or so in the background and respect this data when processing toots). But you're right, this is a little more than what I originally planned it to be. I will definitely think about if a) I have enough time to maintain more features and b) if this should go into FediAct or an extra extension.

Cheers

**Comment by Lartsch** [comment]
This is now fully implemented in v0.9.5:
- Muted/blocked users are treated in the same way (hiding all their boost, toots and toots with mentions of them)
- Domain blocks are respected as well
- It is disabled by default since I do not recommend using it (it can degrade performance or lead to rendering issues - try if it works well for u)

**Comment by tinglycraniumplacidly** [comment]
this is awesome! think it mostly works, there's at least one account in my block list that still shows up?

**Comment by tinglycraniumplacidly** [comment]
THIS IS AMAZING. TY!!!
