### ISSUE TITLE
Using a loading spinner instead of resolving text

### ISSUE THREAD

**Issue by Freeplayg** [Lartsch/FediAct#33]
Saw https://github.com/Lartsch/FediAct/commit/3a5809d73dd99e902298f535ed387fae4c25122b, I think it would make more sense to use a loading icon here, instead (I don't think the X really shows that it's supposed to be loading/resolving)

**Comment by Lartsch** [comment]
The X indicates that resolving failed

**Comment by Freeplayg** [comment]
Oh oops, sorry I didn't realize

Still thinking it could be good to have the loading icon anyways?

**Comment by Lartsch** [comment]
Yes, that'd be prettier. And maybe using an actual icon for the "X".
