### ISSUE TITLE
Starring on external instances doesn't do the star spin animation

### ISSUE THREAD

**Issue by tinglycraniumplacidly** [Lartsch/FediAct#4]
LOL, feel free to close/ignore this if you think it's too petty.

Essentially starring doesn't spin like it does on my local instance. Boosting, however, does have the normal animation. Just something i noticed.

Regardlees, you're my hero. ty!

**Comment by Lartsch** [comment]
Hey :D You're right, totally overlooked that. I added the animation with this commit: https://github.com/Lartsch/FediAct/commit/aed03fe15789d5b55b75103d2fa3810d4c0478b8
It will be included in the next update.

Thanks for letting know!
