### ISSUE TITLE
Options displayed as white on white when in dark mode

### ISSUE THREAD

**Issue by halnine** [Lartsch/FediAct#43]
FediAct 0.9.8.5, Firefox, Windows 11
I use my Firefox with a dark theme. FediAct options (both from icon and from extension options) appear as white text on white background, rendering them unusable.

![image](https://user-images.githubusercontent.com/5073282/209804597-895c88ab-8b87-446e-93c1-34965a914e01.png)

**Comment by Lartsch** [comment]
Hi, thanks for reporting. @Freeplayg Could you take a look at this by any chance?
Cheers

**Comment by Freeplayg** [comment]
The popup/icon works fine for me but yea preferences page is broken, I'll try to see why

**Comment by Freeplayg** [comment]
This is... the weirdest thing...

https://user-images.githubusercontent.com/40742947/209857146-51429f4e-dca1-4ff8-89e0-20e415f5cf45.mp4

**Comment by Freeplayg** [comment]
@halnine Just wondering if the same thing as above happens to you when you try to zoom?

**Comment by Freeplayg** [comment]
> This is... the weirdest thing...
> Screencast.from.2022-12-28.11-04-09.mp4

And is also the worst thing to try and figure out how to fix

**Comment by Lartsch** [comment]
That's odd. I guess the settings page, for some reason, can't handle the flexboxes correctly?

I'm a bit busy with life right now but I'll help with it as soon as I can. Thy @Freeplayg for looking into it.

**Comment by Freeplayg** [comment]
Anything that tries to take the full height does it, `height: 100% & 100vh` does it, as well
