### ISSUE TITLE
Feature Request: ability to vote in a poll

### ISSUE THREAD

**Issue by tinglycraniumplacidly** [Lartsch/FediAct#5]
Not pressing, just noticed voting hasn't been implemented yet.

Said it before in other issues, but this extension is so amazing!! It's so seamless - and honestly the way the Mastodon (and all Fediverse) user experience should be by default (imo). tysm

**Comment by Lartsch** [comment]
Good point! I'll look into it. Thx for suggesting

**Comment by Lartsch** [comment]
I have added support now and it will be included in the next release. At this point, voting is possible from external instances but results have to be viewed on the home instances. Right now, after voting, the vote button is removed and the options are replaced with a link to your home instance.

I might change it so results are displayed right away on the external instance, depending on the effort.

**Comment by tinglycraniumplacidly** [comment]
just voted in a poll. worked great! 👍🏾
