### ISSUE TITLE
Extension prevents me from launching games in Roll20

### ISSUE THREAD

**Issue by WizardShotTheFood** [Lartsch/FediAct#51]
When the FediAct extension is enabled, I am unable to launch my tabletop games in Roll20. Doing so sends me to a Cloudflare "checking to make sure you're not a bot" page, then back to the login screen. After I log in it drops me back to the page I was at where I tried to launch the game. Repeating this skips the Cloudflare page, but sends me back to the login screen.

This is much like the behavior reported in #29. I'm experiencing this on Firefox 108.0.1.

**Comment by Lartsch** [comment]
I suggest adding the site to the blacklist in the FediAct settings. Please reopen if that doesn't fix it. It's probably caused by the initial API call to check if it's a mastodon instance. This will be improved in the future.
