### ISSUE TITLE
Feature: Hide sign-in and create account buttons

### ISSUE THREAD

**Issue by joenepraat** [Lartsch/FediAct#58]
To avoid even less confusion and because it looks neat, I like to request to be able to hide the sign-in and create account buttons. See simple mock-up in the screenshot.
![afbeelding](https://user-images.githubusercontent.com/41594439/211066885-40ad4845-544f-4573-833f-b58cec9109c4.png)

**Comment by Freeplayg** [comment]
How would the user log in to other servers then ?

**Comment by joenepraat** [comment]
FediAct is meant for servers you don't need to log-in. If someone has multiple accounts they can whitelist those servers.

**Comment by Lartsch** [comment]
I understand the request, yet there are some users who would prefer it to stay and also, it does not bring a great value while adding effort to maintain. Might reconsider this in the future, but for now I'll leave the buttons.

Thanks for posting anyways!

**Comment by joenepraat** [comment]
That's a shame. It could be opt-in.
