### ISSUE TITLE
FediAct sometimes runs on logged in pages even when ignore sessions is off

### ISSUE THREAD

**Issue by Freeplayg** [Lartsch/FediAct#59]
![Screenshot from 2023-01-07 14-53-00](https://user-images.githubusercontent.com/40742947/211168611-592b51f6-a3b9-4a39-9bb4-cba43778290c.png)

**Comment by Lartsch** [comment]
Okay, gonna look at this. Which site are you s
browsing?

**Comment by Freeplayg** [comment]
Screenshot is brands.town, I think it also happened in mastodon.online

**Comment by Lartsch** [comment]
Okay. And are you using any theme or so? FediAct needs to look for the <script> element with the id "initial-state", which contains JSON with an "access_token" field

**Comment by Freeplayg** [comment]
I'm going to close this for now as I don't really use the extension much (as my main isn't on Mastodon), sorry for such a late reply though

The only other modifications I have on are Stylus UserStyles which seem to just be added at the end of the HTML
![image](https://user-images.githubusercontent.com/40742947/213737435-0d2a666a-6e8d-4695-be36-96c22926587d.png)
