### ISSUE TITLE
Fediact not working on major instances

### ISSUE THREAD

**Issue by tinglycraniumplacidly** [Lartsch/FediAct#67]
I don't think this is a FediAct software issue per se. Just curious if anyone else is experiencing problems favoriting, etc on the major instances like

1. mastodon.social
2. masto.ai
3. mstdn.social
4. universeodon.com

Probably are more.

Smaller instances seem to work fine.

Is this possibly due to the instance I'm on, that's blocking FediAct requests from certain instances?

**Comment by tinglycraniumplacidly** [comment]
nm, seems to be VPN related.

**Comment by davinkevin** [comment]
`mastodon.social` is not OK for me too. Maybe something related to the 4.3 nightly used there…
