### ISSUE TITLE
Implicit blacklist: Don't redirect actions if already logged in on that instance

### ISSUE THREAD

**Issue by vintprox** [Lartsch/FediAct#7]
How it currently works: it always assumes that all actions must be made on behalf of home instance.

But maybe it should not be the case, if I, for example, have another account on the target instance. Like, I have a home/primary account and I want other instances redirect actions there, but not on instance that I use exclusively for native language communications where I logged in through separate account.

**Comment by Lartsch** [comment]
Hi, good point. I'll add a check if the user is logged in.

**Comment by Lartsch** [comment]
Added with https://github.com/Lartsch/FediAct/commit/db33da9d564c4b479907a63a2fa7b0919eed4744 / v0.9.6.2
