### ISSUE TITLE
Less verbose

### ISSUE THREAD

**Issue by haayman-imagem** [Lartsch/FediAct#8]
I'm a developer and don't like to see your console.log messages when debugging my sites

[FediAct] Request to http://localhost/api/v1/instance failed.
[FediAct] Does not look like a Mastodon instance.
[FediAct] Will not process this site.

Could you please disable these?

(excellent plugin BTW!)

**Comment by Lartsch** [comment]
Hi, you're right, should be disabled. Will be so in the next update. Cheers!

**Comment by Lartsch** [comment]
Fixed with https://github.com/Lartsch/FediAct/commit/db33da9d564c4b479907a63a2fa7b0919eed4744 / v0.9.6.2
